#spring:
#  data:
#    elasticsearch:
#      client:
#        type: rest
#        rest:
#          endpoints: localhost:9200
spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
      path:
        mapping-file: elasticsearch-index-settings.json
    redis:
      host: localhost
      port: 6379
      database: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1016314922111-1l894a7ott039bu528tove309kohlrt6.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
      bindings:
        input-in-0:
          destination: test
          group: test
          content-type: application/json
        output:
          destination: test
          content-type: application/json

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2:  DEBUG